# Generated by Django 4.1.4 on 2022-12-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='proyecto/images/')),
                ('title', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=20)),
                ('github', models.URLField(blank=True)),
            ],
        ),
    ]
